import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

interface SeedDomain {
  name: string;
  extension: string;
  category: string;
  tags: string[];
  shortDescription: string;
  useCases: string[];
  price: number | null;
  showPrice: boolean;
  saleType: string;
  sourceMarketplace: string;
  registrar?: string;
  domainScore?: number;
  tldsTaken?: number;
  expirationDate?: string;
  featured: boolean;
  legalReviewRequired: boolean;
}

const atomDomains: SeedDomain[] = [
  {
    name: 'FogEngine.com',
    extension: '.com',
    category: 'AI',
    tags: ['ai', 'infrastructure', 'cloud', 'engine'],
    shortDescription: 'A strong, technology-oriented name for infrastructure, cloud, AI systems, developer tools, or automation products.',
    useCases: ['AI infrastructure', 'Cloud orchestration', 'Developer tools', 'Data processing', 'Automation platforms'],
    price: 14888,
    showPrice: true,
    saleType: 'BIN',
    sourceMarketplace: 'Atom',
    domainScore: 7.8,
    tldsTaken: 13,
    expirationDate: '2027-03-24',
    featured: true,
    legalReviewRequired: false,
  },
  {
    name: 'FogEngine.ai',
    extension: '.ai',
    category: 'AI',
    tags: ['ai', 'infrastructure', 'cloud'],
    shortDescription: 'A targeted AI extension for a technology brand focused on artificial intelligence or machine learning products.',
    useCases: ['AI platform', 'Machine learning tools', 'AI infrastructure'],
    price: 14888,
    showPrice: true,
    saleType: 'BIN',
    sourceMarketplace: 'Atom',
    domainScore: 5.0,
    tldsTaken: 12,
    expirationDate: '2028-03-27',
    featured: false,
    legalReviewRequired: false,
  },
  {
    name: 'FogEngine.io',
    extension: '.io',
    category: 'Technology',
    tags: ['technology', 'infrastructure', 'developer'],
    shortDescription: 'A developer-focused extension suitable for tech tools, platforms, or developer infrastructure products.',
    useCases: ['Developer tools', 'Tech platform', 'Infrastructure services'],
    price: 8888,
    showPrice: true,
    saleType: 'BIN',
    sourceMarketplace: 'Atom',
    domainScore: 5.9,
    tldsTaken: 12,
    expirationDate: '2027-03-27',
    featured: false,
    legalReviewRequired: false,
  },
  {
    name: 'DnaBite.com',
    extension: '.com',
    category: 'Health',
    tags: ['health', 'biotech', 'genomics'],
    shortDescription: 'A concise name for a health, biotech, or genomics-related product or service.',
    useCases: ['Biotech startup', 'Genomics platform', 'Health tech product', 'DNA testing service'],
    price: 4361,
    showPrice: true,
    saleType: 'BIN',
    sourceMarketplace: 'Atom',
    domainScore: 6.0,
    tldsTaken: 1,
    expirationDate: '2027-04-14',
    featured: false,
    legalReviewRequired: false,
  },
  {
    name: 'KernEngine.com',
    extension: '.com',
    category: 'Technology',
    tags: ['technology', 'engineering', 'infrastructure'],
    shortDescription: 'A technical name suited for a core technology product, compute engine, or systems infrastructure.',
    useCases: ['Compute platform', 'Systems infrastructure', 'Core technology product'],
    price: 5297,
    showPrice: true,
    saleType: 'BIN',
    sourceMarketplace: 'Atom',
    domainScore: 5.3,
    tldsTaken: 2,
    expirationDate: '2027-04-13',
    featured: false,
    legalReviewRequired: false,
  },
  {
    name: 'MythosScale.com',
    extension: '.com',
    category: 'SaaS',
    tags: ['saas', 'scaling', 'infrastructure'],
    shortDescription: 'A memorable name for a scaling, infrastructure, or growth-focused SaaS platform.',
    useCases: ['Scaling platform', 'Infrastructure SaaS', 'Growth tools'],
    price: 3899,
    showPrice: true,
    saleType: 'BIN',
    sourceMarketplace: 'Atom',
    domainScore: 6.1,
    tldsTaken: 3,
    expirationDate: '2027-04-07',
    featured: true,
    legalReviewRequired: false,
  },
  {
    name: 'MythosSync.com',
    extension: '.com',
    category: 'Technology',
    tags: ['technology', 'synchronization', 'data'],
    shortDescription: 'A name suited for data synchronization, integration, or workflow automation products.',
    useCases: ['Data sync platform', 'Workflow automation', 'Integration tools'],
    price: 3899,
    showPrice: true,
    saleType: 'BIN',
    sourceMarketplace: 'Atom',
    domainScore: 5.8,
    tldsTaken: 3,
    expirationDate: '2027-04-07',
    featured: false,
    legalReviewRequired: false,
  },
  {
    name: 'ClawEmbed.com',
    extension: '.com',
    category: 'AI',
    tags: ['ai', 'embedding', 'technology'],
    shortDescription: 'A name for AI embedding solutions, integration tools, or technology products.',
    useCases: ['AI embeddings', 'Integration platform', 'Embedding API'],
    price: 3099,
    showPrice: true,
    saleType: 'BIN',
    sourceMarketplace: 'Atom',
    domainScore: 5.5,
    tldsTaken: 3,
    expirationDate: '2027-04-02',
    featured: false,
    legalReviewRequired: false,
  },
  {
    name: 'TrendDrill.com',
    extension: '.com',
    category: 'Marketing',
    tags: ['marketing', 'analytics', 'trends'],
    shortDescription: 'A practical name for trend analysis, market research, or data-driven marketing tools.',
    useCases: ['Market research tool', 'Trend analytics', 'Data-driven marketing'],
    price: 4361,
    showPrice: true,
    saleType: 'BIN',
    sourceMarketplace: 'Atom',
    domainScore: 5.5,
    tldsTaken: 1,
    expirationDate: '2027-04-06',
    featured: false,
    legalReviewRequired: false,
  },
  {
    name: 'JuvOda.com',
    extension: '.com',
    category: 'Brandable',
    tags: ['brandable', 'youth', 'lifestyle'],
    shortDescription: 'A short, brandable name suitable for a consumer-facing product or service.',
    useCases: ['Consumer brand', 'Lifestyle product', 'Mobile app'],
    price: 4361,
    showPrice: true,
    saleType: 'BIN',
    sourceMarketplace: 'Atom',
    domainScore: 5.5,
    tldsTaken: 1,
    expirationDate: '2027-04-05',
    featured: false,
    legalReviewRequired: false,
  },
  {
    name: 'MagnifyLeads.com',
    extension: '.com',
    category: 'Marketing',
    tags: ['marketing', 'leads', 'saas'],
    shortDescription: 'A clear, descriptive name for a lead generation or marketing optimization platform.',
    useCases: ['Lead generation SaaS', 'Marketing platform', 'Sales tools'],
    price: 2199,
    showPrice: true,
    saleType: 'BIN',
    sourceMarketplace: 'Atom',
    domainScore: 5.3,
    tldsTaken: 1,
    expirationDate: '2027-04-04',
    featured: true,
    legalReviewRequired: false,
  },
  {
    name: 'VectorSift.com',
    extension: '.com',
    category: 'AI',
    tags: ['ai', 'vector', 'data'],
    shortDescription: 'A name for AI vector search, data filtering, or information retrieval products.',
    useCases: ['Vector search platform', 'AI data filtering', 'Information retrieval'],
    price: 3899,
    showPrice: true,
    saleType: 'BIN',
    sourceMarketplace: 'Atom',
    domainScore: 5.8,
    tldsTaken: 4,
    expirationDate: '2027-04-02',
    featured: true,
    legalReviewRequired: false,
  },
  {
    name: 'PriceAutomate.com',
    extension: '.com',
    category: 'SaaS',
    tags: ['saas', 'pricing', 'automation'],
    shortDescription: 'A descriptive name for pricing automation, dynamic pricing, or revenue optimization tools.',
    useCases: ['Pricing automation SaaS', 'Dynamic pricing tool', 'Revenue optimization'],
    price: 5297,
    showPrice: true,
    saleType: 'BIN',
    sourceMarketplace: 'Atom',
    domainScore: 5.2,
    tldsTaken: 3,
    expirationDate: '2027-04-01',
    featured: true,
    legalReviewRequired: false,
  },
  {
    name: 'AshaBot.com',
    extension: '.com',
    category: 'AI',
    tags: ['ai', 'bot', 'automation'],
    shortDescription: 'A friendly, approachable name for a chatbot, AI assistant, or automation bot.',
    useCases: ['AI chatbot', 'Customer service bot', 'Automation assistant'],
    price: 2333,
    showPrice: true,
    saleType: 'BIN',
    sourceMarketplace: 'Atom',
    domainScore: 6.5,
    tldsTaken: 5,
    expirationDate: '2027-03-30',
    featured: true,
    legalReviewRequired: false,
  },
  {
    name: 'TapToWash.com',
    extension: '.com',
    category: 'Local Services',
    tags: ['local services', 'on-demand', 'marketplace'],
    shortDescription: 'A consumer-friendly name for an on-demand washing, cleaning, or local services marketplace.',
    useCases: ['On-demand laundry', 'Cleaning service marketplace', 'Local services app'],
    price: 3899,
    showPrice: true,
    saleType: 'BIN',
    sourceMarketplace: 'Atom',
    domainScore: 5.8,
    tldsTaken: 4,
    expirationDate: '2027-03-31',
    featured: false,
    legalReviewRequired: false,
  },
  {
    name: 'Eleniz.com',
    extension: '.com',
    category: 'Brandable',
    tags: ['brandable', 'elegant', 'fashion'],
    shortDescription: 'A refined, brandable name suitable for fashion, lifestyle, or premium consumer products.',
    useCases: ['Fashion brand', 'Lifestyle product', 'Premium consumer brand'],
    price: 3899,
    showPrice: true,
    saleType: 'BIN',
    sourceMarketplace: 'Atom',
    domainScore: 5.5,
    tldsTaken: 4,
    expirationDate: '2027-03-25',
    featured: false,
    legalReviewRequired: false,
  },
  {
    name: 'AmbitCode.com',
    extension: '.com',
    category: 'Technology',
    tags: ['technology', 'coding', 'developer'],
    shortDescription: 'A technical name for a coding platform, developer tools, or software development product.',
    useCases: ['Developer platform', 'Code tools', 'Software development'],
    price: 3399,
    showPrice: true,
    saleType: 'BIN',
    sourceMarketplace: 'Atom',
    domainScore: 5.5,
    tldsTaken: 1,
    expirationDate: '2026-11-21',
    featured: false,
    legalReviewRequired: false,
  },
  {
    name: 'ShiftLux.com',
    extension: '.com',
    category: 'Brandable',
    tags: ['brandable', 'luxury', 'lifestyle'],
    shortDescription: 'A premium brandable name for luxury services, lifestyle products, or premium marketplaces.',
    useCases: ['Luxury marketplace', 'Premium services', 'Lifestyle brand'],
    price: 3899,
    showPrice: true,
    saleType: 'BIN',
    sourceMarketplace: 'Atom',
    domainScore: 6.3,
    tldsTaken: 1,
    expirationDate: '2026-10-17',
    featured: false,
    legalReviewRequired: false,
  },
  {
    name: 'ComfyUx.com',
    extension: '.com',
    category: 'Technology',
    tags: ['technology', 'ux', 'design'],
    shortDescription: 'A name for UX design tools, user experience platforms, or comfort-focused digital products.',
    useCases: ['UX design platform', 'User experience tools', 'Design SaaS'],
    price: 5297,
    showPrice: true,
    saleType: 'BIN',
    sourceMarketplace: 'Atom',
    domainScore: 6.0,
    tldsTaken: 1,
    expirationDate: '2026-10-10',
    featured: true,
    legalReviewRequired: false,
  },
  {
    name: 'SyncRender.com',
    extension: '.com',
    category: 'Technology',
    tags: ['technology', 'rendering', 'synchronization'],
    shortDescription: 'A name for rendering services, synchronization tools, or cloud-based visualization platforms.',
    useCases: ['Cloud rendering', 'Visualization platform', 'Sync tools'],
    price: 4361,
    showPrice: true,
    saleType: 'BIN',
    sourceMarketplace: 'Atom',
    domainScore: 5.0,
    tldsTaken: 4,
    expirationDate: '2027-04-09',
    featured: true,
    legalReviewRequired: false,
  },
  {
    name: 'CapVerve.com',
    extension: '.com',
    category: 'Fintech',
    tags: ['fintech', 'capital', 'finance'],
    shortDescription: 'A confident name for a fintech product, capital management tool, or financial services brand.',
    useCases: ['Fintech platform', 'Capital management', 'Financial tools'],
    price: 4873,
    showPrice: true,
    saleType: 'BIN',
    sourceMarketplace: 'Atom',
    domainScore: 7.6,
    tldsTaken: 1,
    expirationDate: '2026-10-03',
    featured: true,
    legalReviewRequired: false,
  },
  {
    name: 'FinTriva.com',
    extension: '.com',
    category: 'Finance',
    tags: ['finance', 'fintech', 'data'],
    shortDescription: 'A financial technology name for data, analytics, or financial information products.',
    useCases: ['Financial data platform', 'Fintech analytics', 'Finance tools'],
    price: 3899,
    showPrice: true,
    saleType: 'BIN',
    sourceMarketplace: 'Atom',
    domainScore: 6.1,
    tldsTaken: 2,
    expirationDate: '2026-10-03',
    featured: true,
    legalReviewRequired: false,
  },
  {
    name: 'BulwarkPay.com',
    extension: '.com',
    category: 'Payments',
    tags: ['payments', 'security', 'fintech'],
    shortDescription: 'A security-focused name for payment processing, fintech security, or protected transactions.',
    useCases: ['Payment security', 'Fintech security platform', 'Secure transactions'],
    price: 4999,
    showPrice: true,
    saleType: 'BIN',
    sourceMarketplace: 'Atom',
    domainScore: 5.0,
    tldsTaken: 4,
    expirationDate: '2027-08-22',
    featured: false,
    legalReviewRequired: false,
  },
  {
    name: 'RevRit.com',
    extension: '.com',
    category: 'Brandable',
    tags: ['brandable', 'revenue', 'ritual'],
    shortDescription: 'A compact, memorable name for a SaaS tool, digital product, or business platform.',
    useCases: ['SaaS product', 'Business tool', 'Digital platform'],
    price: 2199,
    showPrice: true,
    saleType: 'BIN',
    sourceMarketplace: 'Atom',
    domainScore: 6.5,
    tldsTaken: 4,
    expirationDate: '2027-08-17',
    featured: true,
    legalReviewRequired: false,
  },
  {
    name: 'FinLyra.com',
    extension: '.com',
    category: 'Finance',
    tags: ['finance', 'fintech', 'analytics'],
    shortDescription: 'An elegant financial name for analytics, investment tools, or fintech products.',
    useCases: ['Financial analytics', 'Investment tools', 'Fintech product'],
    price: 3899,
    showPrice: true,
    saleType: 'BIN',
    sourceMarketplace: 'Atom',
    domainScore: 5.5,
    tldsTaken: 2,
    expirationDate: '2026-10-03',
    featured: true,
    legalReviewRequired: false,
  },
  {
    name: 'NodFit.com',
    extension: '.com',
    category: 'Health',
    tags: ['health', 'fitness', 'wellness'],
    shortDescription: 'A modern name for health, fitness, or wellness technology products.',
    useCases: ['Health tech', 'Fitness app', 'Wellness platform'],
    price: 4595,
    showPrice: true,
    saleType: 'BIN',
    sourceMarketplace: 'Atom',
    domainScore: 6.8,
    tldsTaken: 3,
    expirationDate: '2027-08-22',
    featured: true,
    legalReviewRequired: false,
  },
  {
    name: 'CozyUx.com',
    extension: '.com',
    category: 'Technology',
    tags: ['technology', 'ux', 'design', 'comfort'],
    shortDescription: 'A warm, approachable name for UX-focused design tools or user-friendly digital products.',
    useCases: ['UX design tools', 'User-friendly platform', 'Design agency'],
    price: 5297,
    showPrice: true,
    saleType: 'BIN',
    sourceMarketplace: 'Atom',
    domainScore: 5.5,
    tldsTaken: 1,
    expirationDate: '2026-10-10',
    featured: false,
    legalReviewRequired: false,
  },
];

// Additional portfolio domains (deduplicated, excluding Atom duplicates)
const portfolioDomains: SeedDomain[] = [
  {
    name: 'FogInfra.com',
    extension: '.com',
    category: 'Infrastructure',
    tags: ['infrastructure', 'cloud', 'ai', 'fog computing'],
    shortDescription: 'A cloud infrastructure name for fog computing, distributed systems, or edge AI platforms.',
    useCases: ['Fog computing platform', 'Edge AI infrastructure', 'Distributed systems'],
    featured: true,
    legalReviewRequired: false,
  },
  {
    name: 'AllocEngine.com',
    extension: '.com',
    category: 'Technology',
    tags: ['technology', 'allocation', 'infrastructure'],
    shortDescription: 'A technical name for resource allocation, compute orchestration, or infrastructure management.',
    useCases: ['Resource allocation platform', 'Compute orchestration', 'Infrastructure management'],
    featured: true,
    legalReviewRequired: false,
  },
  {
    name: 'ContainerImage.com',
    extension: '.com',
    category: 'Infrastructure',
    tags: ['infrastructure', 'docker', 'containers', 'devops'],
    shortDescription: 'A descriptive name for container management, Docker tools, or cloud-native infrastructure.',
    useCases: ['Container registry', 'Docker tools', 'Cloud-native platform'],
    featured: true,
    legalReviewRequired: false,
  },
  {
    name: 'ModelCompress.com',
    extension: '.com',
    category: 'AI',
    tags: ['ai', 'machine learning', 'optimization'],
    shortDescription: 'A targeted name for AI model compression, optimization, or machine learning efficiency tools.',
    useCases: ['AI model optimization', 'ML compression tools', 'Model deployment'],
    featured: true,
    legalReviewRequired: false,
  },
  {
    name: 'SnapInference.com',
    extension: '.com',
    category: 'AI',
    tags: ['ai', 'inference', 'machine learning'],
    shortDescription: 'A name for fast AI inference, real-time prediction, or machine learning deployment platforms.',
    useCases: ['AI inference platform', 'Real-time ML predictions', 'Model serving'],
    featured: true,
    legalReviewRequired: false,
  },
  {
    name: 'LoreAGI.com',
    extension: '.com',
    category: 'AI',
    tags: ['ai', 'agi', 'knowledge'],
    shortDescription: 'A name for an AGI research project, knowledge base, or AI development platform.',
    useCases: ['AGI research platform', 'AI knowledge base', 'AI development tools'],
    featured: false,
    legalReviewRequired: false,
  },
  {
    name: 'RoboAlloc.com',
    extension: '.com',
    category: 'AI',
    tags: ['ai', 'robotics', 'allocation'],
    shortDescription: 'A name for AI-driven resource allocation, robotic automation, or intelligent scheduling.',
    useCases: ['AI resource allocation', 'Robotic automation', 'Intelligent scheduling'],
    featured: false,
    legalReviewRequired: false,
  },
  {
    name: 'HumbleEngine.com',
    extension: '.com',
    category: 'Technology',
    tags: ['technology', 'engine', 'developer'],
    shortDescription: 'An approachable name for a developer tool, technology engine, or software platform.',
    useCases: ['Developer tools', 'Software engine', 'Tech platform'],
    featured: false,
    legalReviewRequired: false,
  },
  {
    name: 'LiteGenAI.com',
    extension: '.com',
    category: 'AI',
    tags: ['ai', 'generation', 'lightweight'],
    shortDescription: 'A name for lightweight AI generation tools, efficient LLM platforms, or AI content tools.',
    useCases: ['Lightweight AI tools', 'LLM platform', 'AI content generation'],
    featured: false,
    legalReviewRequired: false,
  },
  {
    name: 'UltraKeryx.com',
    extension: '.com',
    category: 'Brandable',
    tags: ['brandable', 'technology'],
    shortDescription: 'A unique, brandable name for a technology product or digital platform.',
    useCases: ['Tech brand', 'Digital platform', 'Startup name'],
    featured: false,
    legalReviewRequired: false,
  },
  {
    name: 'RaBaLy.com',
    extension: '.com',
    category: 'Brandable',
    tags: ['brandable'],
    shortDescription: 'A short, distinctive brandable name for a consumer or business product.',
    useCases: ['Consumer brand', 'Business name', 'Startup'],
    featured: false,
    legalReviewRequired: false,
  },
  {
    name: 'FlitDo.com',
    extension: '.com',
    category: 'Brandable',
    tags: ['brandable', 'tasks', 'productivity'],
    shortDescription: 'A short, snappy name for a task management, productivity, or quick-action app.',
    useCases: ['Task management app', 'Productivity tool', 'Quick-action platform'],
    featured: false,
    legalReviewRequired: false,
  },
  {
    name: 'TopupChoice.com',
    extension: '.com',
    category: 'E-commerce',
    tags: ['e-commerce', 'topup', 'payments'],
    shortDescription: 'A name for a top-up, reload, or digital payment choice platform.',
    useCases: ['Digital top-up platform', 'Payment choice service', 'Mobile reload'],
    featured: false,
    legalReviewRequired: false,
  },
  {
    name: 'SortedLoans.com',
    extension: '.com',
    category: 'Finance',
    tags: ['finance', 'loans', 'fintech'],
    shortDescription: 'A name for a loan comparison, sorting, or financial marketplace platform.',
    useCases: ['Loan comparison platform', 'Financial marketplace', 'Lending marketplace'],
    featured: false,
    legalReviewRequired: false,
  },
  {
    name: 'FatVox.com',
    extension: '.com',
    category: 'Brandable',
    tags: ['brandable', 'voice', 'audio'],
    shortDescription: 'A memorable name for a voice, audio, or communication technology product.',
    useCases: ['Voice technology', 'Audio platform', 'Communication tool'],
    featured: false,
    legalReviewRequired: false,
  },
  {
    name: 'Intelligence.insure',
    extension: '.insure',
    category: 'Finance',
    tags: ['insurance', 'ai', 'intelligence'],
    shortDescription: 'An AI-focused insurance domain for intelligent insurance products or insurtech platforms.',
    useCases: ['Insurtech platform', 'AI insurance tools', 'Smart insurance'],
    featured: false,
    legalReviewRequired: false,
  },
  {
    name: 'OnChain.voyage',
    extension: '.voyage',
    category: 'Technology',
    tags: ['blockchain', 'web3', 'travel'],
    shortDescription: 'A blockchain/web3 domain for on-chain services or decentralized travel platforms.',
    useCases: ['Web3 platform', 'Blockchain travel', 'On-chain services'],
    featured: false,
    legalReviewRequired: false,
  },
  {
    name: 'Intelligence.voyage',
    extension: '.voyage',
    category: 'Technology',
    tags: ['ai', 'intelligence', 'travel'],
    shortDescription: 'An AI and travel combined domain for intelligent travel planning or AI-powered voyage services.',
    useCases: ['AI travel planning', 'Intelligent voyage services', 'Smart travel'],
    featured: false,
    legalReviewRequired: false,
  },
  {
    name: '1XMR.xyz',
    extension: '.xyz',
    category: 'Technology',
    tags: ['crypto', 'monero', 'blockchain'],
    shortDescription: 'A cryptocurrency domain related to Monero (XMR).',
    useCases: ['Crypto platform', 'XMR-related service'],
    featured: false,
    legalReviewRequired: true,
  },
  {
    name: 'ApexPoster.com',
    extension: '.com',
    category: 'E-commerce',
    tags: ['e-commerce', 'printing', 'design'],
    shortDescription: 'A name for a poster printing, design, or custom print marketplace.',
    useCases: ['Poster printing service', 'Design marketplace', 'Custom prints'],
    featured: false,
    legalReviewRequired: false,
  },
  {
    name: 'AsianBeautySalon.com',
    extension: '.com',
    category: 'Local Services',
    tags: ['local services', 'beauty', 'salon'],
    shortDescription: 'A local services domain for a beauty salon or beauty services directory.',
    useCases: ['Beauty salon', 'Salon booking platform', 'Beauty directory'],
    featured: false,
    legalReviewRequired: false,
  },
  {
    name: 'BasedFX.com',
    extension: '.com',
    category: 'Fintech',
    tags: ['fintech', 'forex', 'trading'],
    shortDescription: 'A fintech name for forex trading, foreign exchange, or financial trading platforms.',
    useCases: ['Forex trading platform', 'FX tools', 'Trading platform'],
    featured: false,
    legalReviewRequired: false,
  },
  {
    name: 'CapitalGigs.xyz',
    extension: '.xyz',
    category: 'Fintech',
    tags: ['fintech', 'gigs', 'freelance'],
    shortDescription: 'A domain for freelance finance, capital gigs, or financial services marketplace.',
    useCases: ['Financial freelance platform', 'Capital services marketplace'],
    featured: false,
    legalReviewRequired: false,
  },
  {
    name: 'DogCo.xyz',
    extension: '.xyz',
    category: 'Brandable',
    tags: ['brandable', 'pets'],
    shortDescription: 'A brandable domain for a pet-related company or product.',
    useCases: ['Pet company', 'Dog products brand', 'Pet services'],
    featured: false,
    legalReviewRequired: false,
  },
  {
    name: 'DAPEJO.com',
    extension: '.com',
    category: 'Brandable',
    tags: ['brandable'],
    shortDescription: 'A unique, short brandable name for a business or product.',
    useCases: ['Brand name', 'Startup', 'Business identity'],
    featured: false,
    legalReviewRequired: false,
  },
  {
    name: 'DinViz.com',
    extension: '.com',
    category: 'Technology',
    tags: ['technology', 'visualization', 'data'],
    shortDescription: 'A name for data visualization, analytics dashboards, or business intelligence tools.',
    useCases: ['Data visualization', 'Analytics dashboard', 'BI tools'],
    featured: false,
    legalReviewRequired: false,
  },
  {
    name: 'OracleGenAI.com',
    extension: '.com',
    category: 'AI',
    tags: ['ai', 'genai', 'oracle'],
    shortDescription: 'An AI-focused domain for generative AI platforms or AI-powered data tools.',
    useCases: ['GenAI platform', 'AI data tools', 'Generative AI service'],
    featured: false,
    legalReviewRequired: true,
  },
  {
    name: 'GlowHairs.com',
    extension: '.com',
    category: 'Local Services',
    tags: ['local services', 'beauty', 'hair'],
    shortDescription: 'A beauty and hair care domain for salon services or hair product brands.',
    useCases: ['Hair salon', 'Beauty brand', 'Hair care products'],
    featured: false,
    legalReviewRequired: false,
  },
  {
    name: 'SEOAutomationAI.com',
    extension: '.com',
    category: 'Marketing',
    tags: ['marketing', 'seo', 'ai', 'automation'],
    shortDescription: 'A descriptive domain for AI-powered SEO automation tools and platforms.',
    useCases: ['SEO automation platform', 'AI SEO tools', 'Search optimization'],
    featured: false,
    legalReviewRequired: false,
  },
  {
    name: 'TokenizationFunds.com',
    extension: '.com',
    category: 'Finance',
    tags: ['finance', 'tokenization', 'blockchain'],
    shortDescription: 'A domain for tokenized fund management or blockchain-based financial products.',
    useCases: ['Tokenized fund platform', 'Blockchain finance', 'Digital assets'],
    featured: false,
    legalReviewRequired: false,
  },
  {
    name: 'agentarya.com',
    extension: '.com',
    category: 'AI',
    tags: ['ai', 'agents'],
    shortDescription: 'A domain for AI agent platforms or autonomous AI systems.',
    useCases: ['AI agent platform', 'Autonomous AI', 'Agent framework'],
    featured: false,
    legalReviewRequired: false,
  },
  {
    name: 'ciberdomain.com',
    extension: '.com',
    category: 'Technology',
    tags: ['technology', 'cyber', 'domain'],
    shortDescription: 'A cybersecurity and domain services related name.',
    useCases: ['Cybersecurity services', 'Domain services'],
    featured: false,
    legalReviewRequired: false,
  },
  {
    name: 'cybrsystems.com',
    extension: '.com',
    category: 'Technology',
    tags: ['technology', 'cyber', 'systems'],
    shortDescription: 'A cybersecurity systems domain for security solutions or tech infrastructure.',
    useCases: ['Cybersecurity solutions', 'Security systems', 'Tech infrastructure'],
    featured: false,
    legalReviewRequired: false,
  },
  {
    name: 'odsnetwork.com',
    extension: '.com',
    category: 'Technology',
    tags: ['technology', 'network'],
    shortDescription: 'A technology network domain for networking solutions or connectivity platforms.',
    useCases: ['Network solutions', 'Connectivity platform', 'Tech services'],
    featured: false,
    legalReviewRequired: false,
  },
  {
    name: 'vsplink.com',
    extension: '.com',
    category: 'Technology',
    tags: ['technology', 'link', 'sharing'],
    shortDescription: 'A short, tech-oriented name for a linking, sharing, or connection platform.',
    useCases: ['Link sharing platform', 'Connection service', 'URL shortener'],
    featured: false,
    legalReviewRequired: false,
  },
  {
    name: 'webforg.com',
    extension: '.com',
    category: 'Technology',
    tags: ['technology', 'web', 'development'],
    shortDescription: 'A web development and digital forging domain.',
    useCases: ['Web development', 'Digital agency', 'Tech services'],
    featured: false,
    legalReviewRequired: false,
  },
  {
    name: 'qserva.com',
    extension: '.com',
    category: 'Technology',
    tags: ['technology', 'services'],
    shortDescription: 'A short, professional domain for a services or SaaS company.',
    useCases: ['SaaS platform', 'Professional services', 'Tech company'],
    featured: false,
    legalReviewRequired: false,
  },
  {
    name: 'biopendium.com',
    extension: '.com',
    category: 'Health',
    tags: ['health', 'biotech', 'encyclopedia'],
    shortDescription: 'A biotech or health knowledge domain for a reference platform or database.',
    useCases: ['Biotech database', 'Health knowledge platform', 'Research tool'],
    featured: false,
    legalReviewRequired: false,
  },
  {
    name: 'labaiagents.com',
    extension: '.com',
    category: 'AI',
    tags: ['ai', 'agents', 'laboratory'],
    shortDescription: 'A domain for AI agent development, testing, or laboratory tools.',
    useCases: ['AI agent testing', 'Agent development platform', 'AI lab tools'],
    featured: false,
    legalReviewRequired: false,
  },
  {
    name: 'autorepairarizona.com',
    extension: '.com',
    category: 'Local Services',
    tags: ['local services', 'auto repair', 'arizona'],
    shortDescription: 'A local auto repair services domain for Arizona.',
    useCases: ['Auto repair shop', 'Local services directory'],
    featured: false,
    legalReviewRequired: true,
  },
  {
    name: 'hermescoreai.com',
    extension: '.com',
    category: 'AI',
    tags: ['ai', 'core', 'technology'],
    shortDescription: 'An AI core technology domain for AI platforms or infrastructure.',
    useCases: ['AI core platform', 'AI infrastructure', 'ML framework'],
    featured: false,
    legalReviewRequired: false,
  },
  {
    name: 'logicfoxai.com',
    extension: '.com',
    category: 'AI',
    tags: ['ai', 'logic', 'technology'],
    shortDescription: 'An AI and logic domain for intelligent reasoning or AI-powered solutions.',
    useCases: ['AI reasoning platform', 'Intelligent automation', 'Logic-based AI'],
    featured: false,
    legalReviewRequired: false,
  },
  {
    name: 'scopingtool.com',
    extension: '.com',
    category: 'SaaS',
    tags: ['saas', 'project management', 'scoping'],
    shortDescription: 'A SaaS domain for project scoping, planning, or management tools.',
    useCases: ['Project scoping tool', 'Planning platform', 'Scope management'],
    featured: false,
    legalReviewRequired: false,
  },
  {
    name: 'gooseengine.com',
    extension: '.com',
    category: 'Technology',
    tags: ['technology', 'engine', 'developer'],
    shortDescription: 'A developer-friendly name for a technology engine or platform.',
    useCases: ['Developer tools', 'Tech engine', 'Software platform'],
    featured: false,
    legalReviewRequired: false,
  },
  {
    name: 'shoetees.com',
    extension: '.com',
    category: 'E-commerce',
    tags: ['e-commerce', 'fashion', 'shoes'],
    shortDescription: 'A fashion e-commerce domain for shoe-related products.',
    useCases: ['Shoe e-commerce', 'Fashion brand', 'Footwear store'],
    featured: false,
    legalReviewRequired: false,
  },
  {
    name: 'agelookup.com',
    extension: '.com',
    category: 'Technology',
    tags: ['technology', 'verification', 'tools'],
    shortDescription: 'A verification and lookup tool domain for age or identity verification.',
    useCases: ['Age verification tool', 'Identity verification', 'Lookup service'],
    featured: false,
    legalReviewRequired: false,
  },
  {
    name: 'callercrew.com',
    extension: '.com',
    category: 'Technology',
    tags: ['technology', 'communication', 'calling'],
    shortDescription: 'A communication domain for calling services, team communication, or VoIP tools.',
    useCases: ['Calling service', 'Team communication', 'VoIP platform'],
    featured: false,
    legalReviewRequired: false,
  },
  {
    name: 'fortbroker.com',
    extension: '.com',
    category: 'Finance',
    tags: ['finance', 'brokerage', 'trading'],
    shortDescription: 'A financial brokerage domain for trading or investment services.',
    useCases: ['Brokerage platform', 'Trading service', 'Investment tools'],
    featured: false,
    legalReviewRequired: false,
  },
  {
    name: 'pandaspanel.com',
    extension: '.com',
    category: 'Technology',
    tags: ['technology', 'analytics', 'dashboard'],
    shortDescription: 'A data analytics and dashboard domain for business intelligence tools.',
    useCases: ['Analytics dashboard', 'Data panel', 'BI tools'],
    featured: false,
    legalReviewRequired: false,
  },
  {
    name: 'transactionfraud.com',
    extension: '.com',
    category: 'Fintech',
    tags: ['fintech', 'fraud', 'security'],
    shortDescription: 'A fintech security domain for fraud detection and transaction security.',
    useCases: ['Fraud detection platform', 'Transaction security', 'Anti-fraud tools'],
    featured: false,
    legalReviewRequired: false,
  },
  {
    name: 'acierate.com',
    extension: '.com',
    category: 'Brandable',
    tags: ['brandable', 'accelerate'],
    shortDescription: 'A brandable name suggesting acceleration, speed, or progress.',
    useCases: ['Tech startup', 'Acceleration platform', 'Growth tools'],
    featured: false,
    legalReviewRequired: false,
  },
  {
    name: 'augusthunt.com',
    extension: '.com',
    category: 'Brandable',
    tags: ['brandable'],
    shortDescription: 'A distinctive brandable name for a business or product.',
    useCases: ['Brand identity', 'Business name', 'Product name'],
    featured: false,
    legalReviewRequired: false,
  },
  {
    name: 'codelocate.com',
    extension: '.com',
    category: 'Technology',
    tags: ['technology', 'coding', 'developer'],
    shortDescription: 'A developer tools domain for code search, location, or management.',
    useCases: ['Code search tool', 'Developer platform', 'Code management'],
    featured: false,
    legalReviewRequired: false,
  },
  {
    name: 'clawchunk.com',
    extension: '.com',
    category: 'Technology',
    tags: ['technology', 'data', 'extraction'],
    shortDescription: 'A data extraction or processing domain for technology products.',
    useCases: ['Data extraction tool', 'Content processing', 'Web scraping'],
    featured: false,
    legalReviewRequired: false,
  },
  {
    name: 'logitclaw.com',
    extension: '.com',
    category: 'AI',
    tags: ['ai', 'logistics', 'machine learning'],
    shortDescription: 'An AI and logistics domain for intelligent logistics or ML-powered supply chain tools.',
    useCases: ['AI logistics', 'Supply chain tools', 'ML-powered logistics'],
    featured: false,
    legalReviewRequired: false,
  },
  {
    name: 'rangerdoc.com',
    extension: '.com',
    category: 'Health',
    tags: ['health', 'documentation', 'ranger'],
    shortDescription: 'A health documentation or records management domain.',
    useCases: ['Health records', 'Documentation platform', 'Medical tools'],
    featured: false,
    legalReviewRequired: false,
  },
  {
    name: 'berrywatch.com',
    extension: '.com',
    category: 'Technology',
    tags: ['technology', 'monitoring', 'watch'],
    shortDescription: 'A monitoring and alerting domain for tech or consumer watch products.',
    useCases: ['Monitoring platform', 'Alert system', 'Smart watch brand'],
    featured: false,
    legalReviewRequired: false,
  },
  {
    name: 'irmotors.com',
    extension: '.com',
    category: 'Technology',
    tags: ['technology', 'motors', 'automotive'],
    shortDescription: 'An automotive or motors technology domain.',
    useCases: ['Automotive tech', 'Motor services', 'EV platform'],
    featured: false,
    legalReviewRequired: false,
  },
  {
    name: 'partnerpods.com',
    extension: '.com',
    category: 'SaaS',
    tags: ['saas', 'partnership', 'collaboration'],
    shortDescription: 'A SaaS domain for partnership management or collaborative workspace tools.',
    useCases: ['Partnership platform', 'Collaboration tools', 'Co-working SaaS'],
    featured: false,
    legalReviewRequired: false,
  },
  {
    name: 'fogagents.com',
    extension: '.com',
    category: 'AI',
    tags: ['ai', 'agents', 'fog'],
    shortDescription: 'An AI agents domain for autonomous agent systems or multi-agent platforms.',
    useCases: ['AI agent platform', 'Multi-agent system', 'Autonomous agents'],
    featured: false,
    legalReviewRequired: false,
  },
  {
    name: 'foginfrastructure.com',
    extension: '.com',
    category: 'Infrastructure',
    tags: ['infrastructure', 'fog computing', 'cloud'],
    shortDescription: 'A cloud infrastructure domain for fog computing or distributed systems.',
    useCases: ['Fog computing infrastructure', 'Distributed systems', 'Cloud services'],
    featured: false,
    legalReviewRequired: false,
  },
  {
    name: 'fognodes.com',
    extension: '.com',
    category: 'Infrastructure',
    tags: ['infrastructure', 'nodes', 'cloud'],
    shortDescription: 'A cloud nodes domain for edge computing or distributed infrastructure.',
    useCases: ['Edge computing nodes', 'Cloud infrastructure', 'Distributed network'],
    featured: false,
    legalReviewRequired: false,
  },
  {
    name: 'fogorchestrator.com',
    extension: '.com',
    category: 'Infrastructure',
    tags: ['infrastructure', 'orchestration', 'cloud'],
    shortDescription: 'A cloud orchestration domain for managing distributed or fog computing systems.',
    useCases: ['Cloud orchestration', 'Fog computing management', 'Infrastructure orchestration'],
    featured: false,
    legalReviewRequired: false,
  },
  {
    name: 'knitpie.com',
    extension: '.com',
    category: 'E-commerce',
    tags: ['e-commerce', 'crafts', 'knitting'],
    shortDescription: 'An e-commerce domain for crafts, knitting, or handmade products.',
    useCases: ['Crafts marketplace', 'Knitting community', 'Handmade products store'],
    featured: false,
    legalReviewRequired: false,
  },
  {
    name: 'similarengine.com',
    extension: '.com',
    category: 'AI',
    tags: ['ai', 'similarity', 'search'],
    shortDescription: 'An AI similarity search or comparison engine domain.',
    useCases: ['Similarity search engine', 'AI comparison tool', 'Content matching'],
    featured: false,
    legalReviewRequired: false,
  },
  {
    name: 'testandplan.com',
    extension: '.com',
    category: 'SaaS',
    tags: ['saas', 'testing', 'planning'],
    shortDescription: 'A testing and planning SaaS domain for quality assurance or project management.',
    useCases: ['QA testing platform', 'Project planning tool', 'Test management'],
    featured: false,
    legalReviewRequired: false,
  },
  {
    name: 'bizarab.com',
    extension: '.com',
    category: 'Brandable',
    tags: ['brandable'],
    shortDescription: 'A unique brandable name for a creative or unconventional brand.',
    useCases: ['Creative brand', 'Startup name', 'Product identity'],
    featured: false,
    legalReviewRequired: false,
  },
  {
    name: 'cssbrain.com',
    extension: '.com',
    category: 'Technology',
    tags: ['technology', 'css', 'design'],
    shortDescription: 'A CSS and web design domain for styling tools or design resources.',
    useCases: ['CSS tools', 'Design resource platform', 'Web styling'],
    featured: false,
    legalReviewRequired: false,
  },
  {
    name: 'fogedgeai.com',
    extension: '.com',
    category: 'AI',
    tags: ['ai', 'edge computing', 'fog'],
    shortDescription: 'An edge AI domain for fog and edge computing AI systems.',
    useCases: ['Edge AI platform', 'Fog computing AI', 'Distributed AI'],
    featured: false,
    legalReviewRequired: false,
  },
  {
    name: 'proxycluster.com',
    extension: '.com',
    category: 'Infrastructure',
    tags: ['infrastructure', 'proxy', 'networking'],
    shortDescription: 'A proxy and networking domain for proxy management or cluster services.',
    useCases: ['Proxy management', 'Network clustering', 'IP rotation service'],
    featured: false,
    legalReviewRequired: false,
  },
  {
    name: 'scalableaiengine.com',
    extension: '.com',
    category: 'AI',
    tags: ['ai', 'scalable', 'engine'],
    shortDescription: 'A scalable AI engine domain for enterprise AI or ML infrastructure.',
    useCases: ['Scalable AI platform', 'Enterprise ML', 'AI infrastructure'],
    featured: false,
    legalReviewRequired: false,
  },
  {
    name: 'aitherapyapp.com',
    extension: '.com',
    category: 'Health',
    tags: ['health', 'ai', 'therapy'],
    shortDescription: 'An AI therapy app domain for mental health or wellness applications.',
    useCases: ['AI therapy app', 'Mental health platform', 'Wellness application'],
    featured: false,
    legalReviewRequired: false,
  },
  {
    name: '1xmr.com',
    extension: '.com',
    category: 'Technology',
    tags: ['crypto', 'monero'],
    shortDescription: 'A cryptocurrency domain related to Monero (XMR).',
    useCases: ['Crypto service', 'XMR platform'],
    featured: false,
    legalReviewRequired: true,
  },
  {
    name: 'sitewebai.com',
    extension: '.com',
    category: 'AI',
    tags: ['ai', 'web', 'website'],
    shortDescription: 'An AI website builder or web-related AI tools domain.',
    useCases: ['AI website builder', 'Web AI tools', 'Automated web design'],
    featured: false,
    legalReviewRequired: false,
  },
  {
    name: 'brightwavehub.com',
    extension: '.com',
    category: 'Brandable',
    tags: ['brandable', 'media', 'hub'],
    shortDescription: 'A media or content hub domain with a positive, bright brand identity.',
    useCases: ['Content hub', 'Media platform', 'Community hub'],
    featured: false,
    legalReviewRequired: false,
  },
  {
    name: 'salesrobotlabs.com',
    extension: '.com',
    category: 'SaaS',
    tags: ['saas', 'sales', 'automation'],
    shortDescription: 'A sales automation and AI-powered sales tools domain.',
    useCases: ['Sales automation SaaS', 'AI sales tools', 'Lead generation'],
    featured: false,
    legalReviewRequired: false,
  },
  {
    name: 'clickjs.com',
    extension: '.com',
    category: 'Technology',
    tags: ['technology', 'javascript', 'click'],
    shortDescription: 'A short, tech-oriented domain for a JavaScript-related product or click-tracking tool.',
    useCases: ['JS library', 'Click tracking tool', 'Web interaction platform'],
    featured: false,
    legalReviewRequired: false,
  },
  {
    name: 'insightpayai.com',
    extension: '.com',
    category: 'Fintech',
    tags: ['fintech', 'ai', 'payments', 'insights'],
    shortDescription: 'An AI-powered fintech domain for payment insights or financial analytics.',
    useCases: ['Payment analytics', 'AI fintech tools', 'Financial insights'],
    featured: false,
    legalReviewRequired: false,
  },
  {
    name: 'nichedapp.com',
    extension: '.com',
    category: 'Technology',
    tags: ['technology', 'apps', 'niche'],
    shortDescription: 'A niche app development or marketplace domain.',
    useCases: ['Niche app store', 'App development platform', 'Specialized marketplace'],
    featured: false,
    legalReviewRequired: false,
  },
  {
    name: '5damat-aldalil.com',
    extension: '.com',
    category: 'Local Services',
    tags: ['local services'],
    shortDescription: 'A local services domain.',
    useCases: ['Local business', 'Service directory'],
    featured: false,
    legalReviewRequired: false,
  },
  {
    name: 'baseopolis.com',
    extension: '.com',
    category: 'Technology',
    tags: ['technology', 'base', 'platform'],
    shortDescription: 'A technology platform domain suggesting a base or foundation for digital services.',
    useCases: ['Tech platform', 'Digital base', 'Foundation service'],
    featured: false,
    legalReviewRequired: false,
  },
  {
    name: 'lolud.com',
    extension: '.com',
    category: 'Brandable',
    tags: ['brandable'],
    shortDescription: 'A short, brandable domain name.',
    useCases: ['Brand name', 'Startup', 'Product identity'],
    featured: false,
    legalReviewRequired: false,
  },
  {
    name: 'vividforgeai.com',
    extension: '.com',
    category: 'AI',
    tags: ['ai', 'creative', 'generation'],
    shortDescription: 'An AI creative domain for content generation, design, or creative AI tools.',
    useCases: ['AI content generation', 'Creative AI tools', 'Design automation'],
    featured: false,
    legalReviewRequired: false,
  },
  {
    name: 'urgenteyeglasses.com',
    extension: '.com',
    category: 'E-commerce',
    tags: ['e-commerce', 'eyewear', 'health'],
    shortDescription: 'An e-commerce domain for urgent or fast-delivery eyeglasses.',
    useCases: ['Eyewear e-commerce', 'Fast delivery glasses', 'Optical store'],
    featured: false,
    legalReviewRequired: false,
  },
  {
    name: 'zurichgpt.com',
    extension: '.com',
    category: 'AI',
    tags: ['ai', 'gpt'],
    shortDescription: 'An AI/GPT related domain.',
    useCases: ['AI platform', 'GPT service', 'Chatbot'],
    featured: false,
    legalReviewRequired: true,
  },
  {
    name: 'capitalgigs.com',
    extension: '.com',
    category: 'Fintech',
    tags: ['fintech', 'gigs', 'freelance'],
    shortDescription: 'A financial freelance or gig economy domain.',
    useCases: ['Financial freelance platform', 'Gig economy service', 'Capital marketplace'],
    featured: false,
    legalReviewRequired: false,
  },
  {
    name: 'checkoutcircuit.com',
    extension: '.com',
    category: 'E-commerce',
    tags: ['e-commerce', 'checkout', 'payments'],
    shortDescription: 'An e-commerce checkout optimization or payment processing domain.',
    useCases: ['Checkout optimization', 'Payment processing', 'E-commerce tools'],
    featured: false,
    legalReviewRequired: false,
  },
  {
    name: 'topuparabia.com',
    extension: '.com',
    category: 'E-commerce',
    tags: ['e-commerce', 'topup', 'payments'],
    shortDescription: 'A top-up and digital payment domain for the Arab market.',
    useCases: ['Digital top-up service', 'Mobile reload platform', 'Payment service'],
    featured: false,
    legalReviewRequired: false,
  },
  {
    name: 'validomain.com',
    extension: '.com',
    category: 'Technology',
    tags: ['technology', 'domains', 'validation'],
    shortDescription: 'A domain validation or appraisal service domain.',
    useCases: ['Domain validation tool', 'Domain appraisal', 'Domain services'],
    featured: false,
    legalReviewRequired: false,
  },
  {
    name: 'bidnil.com',
    extension: '.com',
    category: 'Fintech',
    tags: ['fintech', 'bidding', 'auction'],
    shortDescription: 'A bidding or auction platform domain.',
    useCases: ['Auction platform', 'Bidding service', 'Marketplace'],
    featured: false,
    legalReviewRequired: false,
  },
  {
    name: 'nopips.com',
    extension: '.com',
    category: 'Fintech',
    tags: ['fintech', 'trading', 'forex'],
    shortDescription: 'A forex or trading domain with a no-loss positioning angle.',
    useCases: ['Trading platform', 'Forex tools', 'Risk-free trading'],
    featured: false,
    legalReviewRequired: false,
  },
  {
    name: 'raphip.com',
    extension: '.com',
    category: 'Brandable',
    tags: ['brandable'],
    shortDescription: 'A short, catchy brandable domain.',
    useCases: ['Brand name', 'Mobile app', 'Startup'],
    featured: false,
    legalReviewRequired: false,
  },
  {
    name: 'softskilltrainers.com',
    extension: '.com',
    category: 'SaaS',
    tags: ['saas', 'education', 'training'],
    shortDescription: 'A soft skills training and education platform domain.',
    useCases: ['Training platform', 'Education SaaS', 'Skill development'],
    featured: false,
    legalReviewRequired: false,
  },
  {
    name: 'sparklepayments.com',
    extension: '.com',
    category: 'Payments',
    tags: ['payments', 'fintech'],
    shortDescription: 'A payment processing domain with a bright, approachable brand identity.',
    useCases: ['Payment platform', 'Fintech service', 'Digital payments'],
    featured: false,
    legalReviewRequired: false,
  },
  {
    name: 'speedindicators.com',
    extension: '.com',
    category: 'Technology',
    tags: ['technology', 'analytics', 'performance'],
    shortDescription: 'A performance analytics or speed monitoring domain.',
    useCases: ['Performance monitoring', 'Speed analytics', 'Web performance tools'],
    featured: false,
    legalReviewRequired: false,
  },
  {
    name: 'vacace.com',
    extension: '.com',
    category: 'Brandable',
    tags: ['brandable', 'vacation'],
    shortDescription: 'A brandable vacation or travel-related domain.',
    useCases: ['Travel brand', 'Vacation platform', 'Booking service'],
    featured: false,
    legalReviewRequired: false,
  },
  {
    name: 'validatortest.com',
    extension: '.com',
    category: 'Technology',
    tags: ['technology', 'validation', 'testing'],
    shortDescription: 'A testing and validation services domain.',
    useCases: ['Validation service', 'Testing platform', 'QA tools'],
    featured: false,
    legalReviewRequired: false,
  },
  {
    name: 'casnex.com',
    extension: '.com',
    category: 'Finance',
    tags: ['finance', 'fintech', 'casino'],
    shortDescription: 'A finance or fintech domain with a casino or gaming angle.',
    useCases: ['Fintech platform', 'Gaming finance', 'Payment solution'],
    featured: false,
    legalReviewRequired: false,
  },
  {
    name: 'fintelva.com',
    extension: '.com',
    category: 'Finance',
    tags: ['finance', 'fintech', 'intelligence'],
    shortDescription: 'A financial intelligence or fintech analytics domain.',
    useCases: ['Financial analytics', 'Fintech intelligence', 'Market insights'],
    featured: false,
    legalReviewRequired: false,
  },
  {
    name: 'fintechxl.com',
    extension: '.com',
    category: 'Fintech',
    tags: ['fintech', 'technology', 'excel'],
    shortDescription: 'A fintech and technology domain suggesting excellence or extra-large capabilities.',
    useCases: ['Fintech platform', 'Tech solutions', 'Financial technology'],
    featured: false,
    legalReviewRequired: false,
  },
  {
    name: 'healthsupplementscanada.com',
    extension: '.com',
    category: 'Health',
    tags: ['health', 'supplements', 'canada'],
    shortDescription: 'A health supplements domain for the Canadian market.',
    useCases: ['Health supplements store', 'Canadian health products', 'Supplements brand'],
    featured: false,
    legalReviewRequired: false,
  },
  {
    name: 'monkeypens.com',
    extension: '.com',
    category: 'E-commerce',
    tags: ['e-commerce', 'writing', 'stationery'],
    shortDescription: 'A stationery or writing instruments e-commerce domain.',
    useCases: ['Stationery store', 'Writing instruments', 'Pen e-commerce'],
    featured: false,
    legalReviewRequired: false,
  },
  {
    name: 'ontariopetcare.com',
    extension: '.com',
    category: 'Local Services',
    tags: ['local services', 'pets', 'ontario'],
    shortDescription: 'A pet care services domain for Ontario, Canada.',
    useCases: ['Pet care services', 'Veterinary clinic', 'Pet sitting'],
    featured: false,
    legalReviewRequired: false,
  },
  {
    name: 'pamperpetcare.com',
    extension: '.com',
    category: 'Local Services',
    tags: ['local services', 'pets', 'care'],
    shortDescription: 'A premium pet care services domain.',
    useCases: ['Premium pet care', 'Pet grooming', 'Pet services'],
    featured: false,
    legalReviewRequired: false,
  },
  {
    name: 'petkik.com',
    extension: '.com',
    category: 'E-commerce',
    tags: ['e-commerce', 'pets'],
    shortDescription: 'A pet products or pet services e-commerce domain.',
    useCases: ['Pet e-commerce', 'Pet products store', 'Pet supplies'],
    featured: false,
    legalReviewRequired: false,
  },
  {
    name: 'eatphoto.com',
    extension: '.com',
    category: 'E-commerce',
    tags: ['e-commerce', 'food', 'photography'],
    shortDescription: 'A food photography or food-related visual content domain.',
    useCases: ['Food photography', 'Restaurant visual content', 'Food media'],
    featured: false,
    legalReviewRequired: false,
  },
  {
    name: 'dailytradingstrategy.com',
    extension: '.com',
    category: 'Finance',
    tags: ['finance', 'trading', 'strategy'],
    shortDescription: 'A daily trading strategy or financial education domain.',
    useCases: ['Trading education', 'Daily strategy platform', 'Financial content'],
    featured: false,
    legalReviewRequired: false,
  },
  {
    name: 'neopaynow.com',
    extension: '.com',
    category: 'Payments',
    tags: ['payments', 'fintech', 'neo'],
    shortDescription: 'A modern payment processing or fintech domain.',
    useCases: ['Payment platform', 'Fintech solution', 'Digital payments'],
    featured: false,
    legalReviewRequired: false,
  },
  {
    name: 'oilsilo.com',
    extension: '.com',
    category: 'E-commerce',
    tags: ['e-commerce', 'oil', 'storage'],
    shortDescription: 'An oil storage or petroleum-related e-commerce domain.',
    useCases: ['Oil marketplace', 'Petroleum services', 'Energy trading'],
    featured: false,
    legalReviewRequired: false,
  },
  {
    name: 'upgradebots.com',
    extension: '.com',
    category: 'AI',
    tags: ['ai', 'bots', 'automation'],
    shortDescription: 'An AI bots and automation upgrade domain.',
    useCases: ['AI bot platform', 'Automation tools', 'Bot upgrade service'],
    featured: false,
    legalReviewRequired: false,
  },
  {
    name: 'torontogiftsdelivery.com',
    extension: '.com',
    category: 'Local Services',
    tags: ['local services', 'gifts', 'toronto', 'delivery'],
    shortDescription: 'A gift delivery service domain for Toronto.',
    useCases: ['Gift delivery service', 'Toronto local business', 'Gift e-commerce'],
    featured: false,
    legalReviewRequired: false,
  },
  // FogEngine additional TLDs
  { name: 'fogengine.co', extension: '.co', category: 'Technology', tags: ['technology', 'fog'], shortDescription: 'FogEngine on .co extension.', useCases: ['Tech brand'], featured: false, legalReviewRequired: false },
  { name: 'fogengine.net', extension: '.net', category: 'Technology', tags: ['technology', 'fog'], shortDescription: 'FogEngine on .net extension.', useCases: ['Tech brand'], featured: false, legalReviewRequired: false },
  { name: 'fogengine.one', extension: '.one', category: 'Technology', tags: ['technology', 'fog'], shortDescription: 'FogEngine on .one extension.', useCases: ['Tech brand'], featured: false, legalReviewRequired: false },
  { name: 'fogengine.online', extension: '.online', category: 'Technology', tags: ['technology', 'fog'], shortDescription: 'FogEngine on .online extension.', useCases: ['Online platform'], featured: false, legalReviewRequired: false },
  { name: 'fogengine.org', extension: '.org', category: 'Technology', tags: ['technology', 'fog'], shortDescription: 'FogEngine on .org extension.', useCases: ['Organization'], featured: false, legalReviewRequired: false },
  { name: 'fogengine.site', extension: '.site', category: 'Technology', tags: ['technology', 'fog'], shortDescription: 'FogEngine on .site extension.', useCases: ['Website'], featured: false, legalReviewRequired: false },
  { name: 'fogengine.space', extension: '.space', category: 'Technology', tags: ['technology', 'fog'], shortDescription: 'FogEngine on .space extension.', useCases: ['Tech platform'], featured: false, legalReviewRequired: false },
  { name: 'fogengine.store', extension: '.store', category: 'E-commerce', tags: ['e-commerce', 'fog'], shortDescription: 'FogEngine on .store extension.', useCases: ['Online store'], featured: false, legalReviewRequired: false },
  { name: 'fogengine.xyz', extension: '.xyz', category: 'Technology', tags: ['technology', 'fog'], shortDescription: 'FogEngine on .xyz extension.', useCases: ['Tech brand'], featured: false, legalReviewRequired: false },
  { name: 'fogengine.si', extension: '.si', category: 'Technology', tags: ['technology', 'fog'], shortDescription: 'FogEngine on .si extension.', useCases: ['Slovenian market'], featured: false, legalReviewRequired: false },
  { name: 'ELENIZ.xyz', extension: '.xyz', category: 'Brandable', tags: ['brandable', 'fashion'], shortDescription: 'Eleniz on .xyz extension.', useCases: ['Brand name'], featured: false, legalReviewRequired: false },
  // Turkish domains
  { name: 'easyposegypt.com', extension: '.com', category: 'Technology', tags: ['technology', 'pos', 'egypt'], shortDescription: 'A POS solutions domain for Egypt.', useCases: ['POS solutions', 'Payment processing'], featured: false, legalReviewRequired: false },
  { name: 'posegypt.com', extension: '.com', category: 'Technology', tags: ['technology', 'pos', 'egypt'], shortDescription: 'A POS services domain for Egypt.', useCases: ['POS services', 'Payment solutions'], featured: false, legalReviewRequired: false },
  { name: 'smartposegypt.com', extension: '.com', category: 'Technology', tags: ['technology', 'pos', 'egypt'], shortDescription: 'A smart POS solutions domain for Egypt.', useCases: ['Smart POS', 'Payment technology'], featured: false, legalReviewRequired: false },
  { name: 'egyptpos.com', extension: '.com', category: 'Technology', tags: ['technology', 'pos', 'egypt'], shortDescription: 'An Egypt POS services domain.', useCases: ['POS platform', 'Egypt payments'], featured: false, legalReviewRequired: false },
  { name: 'sipup.com.tr', extension: '.com.tr', category: 'Brandable', tags: ['brandable', 'turkey'], shortDescription: 'A Turkish brandable domain.', useCases: ['Turkish brand', 'Local service'], featured: false, legalReviewRequired: false },
  { name: 'sipup.tr', extension: '.tr', category: 'Brandable', tags: ['brandable', 'turkey'], shortDescription: 'A Turkish brandable domain.', useCases: ['Turkish brand'], featured: false, legalReviewRequired: false },
  // Huhhi from Atom
  { name: 'huhhi.com', extension: '.com', category: 'Brandable', tags: ['brandable'], shortDescription: 'A short, brandable domain name.', useCases: ['Brand name', 'Startup'], featured: false, legalReviewRequired: false },
];

function slugify(name: string): string {
  return name.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '');
}

function getExtension(name: string): string {
  const match = name.match(/(\.[a-z.]+)$/i);
  return match ? match[1].toLowerCase() : '.com';
}

async function main() {
  console.log('Seeding database...');

  // Clear existing data
  await prisma.inquiry.deleteMany();
  await prisma.domain.deleteMany();
  await prisma.siteSettings.deleteMany();

  // Combine all domains
  const allDomains = [...atomDomains, ...portfolioDomains];

  // Deduplicate by normalized name
  const seen = new Set<string>();
  const uniqueDomains: SeedDomain[] = [];

  for (const d of allDomains) {
    const normalized = d.name.toLowerCase();
    if (!seen.has(normalized)) {
      seen.add(normalized);
      uniqueDomains.push(d);
    }
  }

  console.log(`Seeding ${uniqueDomains.length} unique domains...`);

  // Insert domains
  for (const d of uniqueDomains) {
    const extension = d.extension || getExtension(d.name);
    const normalizedName = d.name.toLowerCase();
    const slug = slugify(d.name);

    await prisma.domain.create({
      data: {
        name: d.name,
        normalizedName,
        slug,
        extension,
        category: d.category || 'Brandable',
        tags: JSON.stringify(d.tags || []),
        shortDescription: d.shortDescription || '',
        useCases: JSON.stringify(d.useCases || []),
        status: 'Available',
        featured: d.featured || false,
        price: d.price ?? null,
        showPrice: d.showPrice ?? false,
        saleType: d.saleType || 'Make an Offer',
        sourceMarketplace: d.sourceMarketplace || null,
        registrar: d.registrar || null,
        domainScore: d.domainScore ?? null,
        tldsTaken: d.tldsTaken ?? null,
        expirationDate: d.expirationDate ? new Date(d.expirationDate) : null,
        legalReviewRequired: d.legalReviewRequired || false,
      },
    });
  }

  // Mark wholesale domains: $99 BIN, showPrice=true, sourceMarketplace='Wholesale'
  // These are the 18 fixed-price BIN names displayed on the homepage Wholesale section.
  const WHOLESALE_NAMES = [
    'healthsupplementscanada.com',
    'checkoutcircuit.com',
    'pamperpetcare.com',
    'raphip.com',
    'torontogiftsdelivery.com',
    'urgenteyeglasses.com',
    '5damat-aldalil.com',
    'testandplan.com',
    'sitewebai.com',
    'monkeypens.com',
    'eatphoto.com',
    'validatortest.com',
    'bizarab.com',
    'brightwavehub.com',
    'nichedapp.com',
    'softskilltrainers.com',
    'dailytradingstrategy.com',
    'ciberdomain.com',
  ];
  await prisma.domain.updateMany({
    where: { name: { in: WHOLESALE_NAMES } },
    data: {
      price: 99,
      showPrice: true,
      saleType: 'BIN',
      sourceMarketplace: 'Wholesale',
      publicNotes: 'Wholesale pricing — first come, first served.',
    },
  });

  // Create default site settings
  await prisma.siteSettings.create({
    data: {
      contactEmail: 'info@nizarrahme.com',
      socialLinks: JSON.stringify({
        x: 'https://x.com/mr_nizarrahme',
        linkedin: 'https://www.linkedin.com/in/nizarrahme/',
        instagram: 'https://www.instagram.com/mr_nizarrahme/',
        facebook: 'https://www.facebook.com/mr.nizarrahme',
      }),
    },
  });

  const totalDomains = await prisma.domain.count();
  const featuredCount = await prisma.domain.count({ where: { featured: true } });
  console.log(`Seeded ${totalDomains} domains (${featuredCount} featured)`);
  console.log('Done!');
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
